### PR TITLE
add a cart dump command

### PR DESCRIPTION
**Pull request by karcaw**
### Description

A Tool to dump all the carts out in yaml, or json

### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable

### CODE REVIEW

**Review by dmlb2000 — APPROVED** [review]
This looks good to me for now.

The other option is to save the initial request that was sent to create the cart. Then dump the request when you run the dump command. There are some give and take with either approach, it depends on what this command is going to be used for in the future.

**Review by dmlb2000 — CHANGES_REQUESTED** [review]
Docker test needs to be fixed

**Comment by karcaw** [comment]
@dmlb2000 fixed docker

**Comment by dmlb2000** [comment]
Seems from my searching that Windows allows unicode environment variables, which doesn't work in Python 2.7. So, not sure what Windows Environment variable is unicode in Appveyor but that might be the issue.

**Comment by dmlb2000** [comment]
https://stackoverflow.com/questions/29429008/what-is-the-proper-way-of-dealing-with-unicode-subprocess-envs-in-windows

**Comment by dmlb2000** [comment]
I'm half tempted at this point to chuck Python 2 for this repo...

**Comment by karcaw** [comment]
@dmlb2000 can we merge this please, and you can pull out python 2 on another branch?

**Review by dmlb2000 — APPROVED** [review]
I think this works for me now...

**Pull request merged**
